### ISSUE TITLE
Build to aim for

### ISSUE THREAD

**Issue by Ardenian** [Ardenian/MyInformationCrawler#1]
We have several options to choose from, what our MIC should be at the end. My favorite options are:
- Windows Form or another kind of local application and database
- A functional website, with login and user account, storing databases online ( server)
- A script for temporary use, no permanent database

Personally, at the very end, I would prefer a website, due to capacities and features I would like to add. 
A script doesn't seem very comfortable to me. While the script solution would not influence the search functionality, it prevents features like collected databases to certain features. 
A local application, like Windows Form, does allow everything I would like to realize, however, would completely cut off everything related to a potential community and features requiring input of more than one user ( reviews, statistics, ratings, ...)

**Comment by Idrinth** [comment]
Moving from .NET to something less selective about it's enviroment(due to similarities I'd propose Java) might help with making number 1 and 2 possible.

**Comment by Ardenian** [comment]
Considered solved.
